### PR TITLE
Production ready chart

### LINKED ISSUE #5: Production ready chart
Hello @shyim 

First of all, thank you for you work. I use you docker images.

As a Kubernetes fan I come across this repository. Unfortunately it's not production ready. 

So based on this I created my own one. Maybe you could take a look into this?
https://github.com/robjuz/helm-charts/tree/master/charts/shopware

I would also appreciate an advice how to automatically keep tracking changes in other branches and trigger a release of a new version, when a need docker image is ready?

### PR DESCRIPTION
**Pull request by robjuz**
resolve #5

### CODE REVIEW

**Comment by robjuz** [comment]
@shyim I see there some leftovers referencing me and wordpress but you could take the first loook

**Comment by robjuz** [comment]
@shyim Have you had time to look on this? What do you think?

**Comment by shyim** [comment]
Hey,

It looks good from my side. One question, would you like want to maintain it further more? I would suggest then moving it into the FriendsOfShopware organization :)

**Comment by robjuz** [comment]
I'm not a helm expert yet, but yes, I would maintain it.
The version from my repo is also available as helm repo and is published on [artifacthub.org](https://artifacthub.io/)

**Comment by shyim** [comment]
Thanks :)

**Pull request merged**
